# Generated by Django 6.0.1 on 2026-01-24 00:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("phone", models.CharField(blank=True, default="", max_length=40)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "instagram_handle",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="customers_c_name_f018e2_idx"),
                    models.Index(fields=["phone"], name="customers_c_phone_8493fa_idx"),
                    models.Index(fields=["email"], name="customers_c_email_4fdeb3_idx"),
                ],
            },
        ),
    ]
